config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'spotify/search'

  resources :tracks
  resources :playlists


  root to: 'tracks#index'
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base

  validates_presence_of :name, :number_of_votes
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates_presence_of :title, :album, :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :authenticate_user!

  def index
    @playlists = Playlist.all
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.new(playlist_params)
    if @playlist.save
      redirect_to @playlist
    else
      render :new
    end

  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, :number_of_votes)
  end

end

app/controllers/spotify_controller.rb
class SpotifyController < ApplicationController
  def search
    title = params[:title]
    if title
      @results = RSpotify::Artist.search(title)
    end
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:title, :album, :artist)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/spotify_helper.rb
module SpotifyHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musicapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>

<%= yield %>

</body>
</html>

app/views/playlists/index.html.erb
<h1>Listado de listas de reproduccion</h1>

<table>
        <thead>
                <tr>
                        <th>Name</th>
                        <th>Number of votes</th>
                </tr>
        </thead>
        <tbody>
          <% @playlists.each do |playlist| %>
            <tr>
                    <td><%= playlist.name %></td>
                    <td><%= playlist.number_of_votes %></td>
            </tr>
          <% end %>
        </tbody>
</table>

app/views/playlists/new.html.erb
<%= form_for(@playlist) do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :number_of_votes %>
        <%= f.text_field :number_of_votes %>

        <%= f.submit %>
<% end %>

app/views/playlists/show.html.erb
<p>
<strong>Name: </strong>
<%= @playlist.name %>
</p>

<p>
<strong>Number of votes: </strong>
<%= @playlist.number_of_votes %>
</p>

app/views/spotify/search.html.erb
<h1>Resultados de busqueda</h1>
<ul>
<% @results.each do |result| %>

        <li><%= result.name %> </li>
<% end %>
</ul>

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :album %><br>
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Album</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.title %></td>
        <td><%= track.album %></td>
        <td><%= track.artist %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>

<%= form_tag(spotify_search_path, method: :get) do  %>
        <%= text_field_tag :title %>
        <%= submit_tag 'Search' %>
<% end %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @track.title %>
</p>

<p>
  <strong>Album:</strong>
  <%= @track.album %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @track.artist %>
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>